dist: trusty
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

language: node_js

git:
  depth: false

node_js:
  - 8
#   - 10
#   - 12

script:
  - npm run-script lint
  - npm run build
  - npm test

cache:
  directories:
    - node_modules
